# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Links
excerpt_separator: <!--more-->
contact_form: https://fordpark.wufoo.com/forms/contact-me/
description: > # this means to ignore newlines until "baseurl:"
  From supporting bespoke software for blue chip companies in Hammersmith to onsite support at a international law firm 
  in Mayfair to director of live experience at a city centre church in Glasgow to Airbnb Superhost (sorry?) to something
  to do with sensors.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: 
github_username:

# Build settings
markdown: kramdown
exclude: [daringfireball.sh]